robot_communication:
  ros__parameters:
    network_ip: "192.168.31.208"
    network_port: 12130
    multi_positionX: 0.0
    multi_positionY: 0.0
    multi_positionZ: 0.0
    multi_rotateR: 0.0
    multi_rotateP: 0.0
    multi_rotateY: 0.0