lidar_transform:
  ros__parameters:
    lidar_positionX: 0.0
    lidar_positionY: 0.0
    lidar_positionZ: 0.0
    lidar_rotateR: 0.0
    lidar_rotateP: 0.0
    lidar_rotateY: 0.0

    camera_positionX: 0.0
    camera_positionY: 0.0
    camera_positionZ: 0.0
    camera_rotateR: 0.0
    camera_rotateP: 0.0
    camera_rotateY: 0.0